# -*- coding: utf-8 -*-
"""Traducao para ingles: Fase 1 (triagem e perguntas de centro).

Formato: id -> {'c': cenario, 'a': [alternativas na ordem do gerador]}.
A alternativa "nenhuma dessas" fica fora, traduzida pelo gerador.
"""

DADOS = {'f1_01': {'c': 'When you were a child and you cried or got scared, what usually happened at home?',
           'a': ['I hardened up. Crying there meant handing over a weak spot, and I was not going to be at '
                 'anyone’s mercy.',
                 'I calmed myself down and let it pass. Making it a subject would only weigh the house down.',
                 'I swallowed it and corrected myself. Crying meant losing my composure, and I had to set '
                 'the example.',
                 'I looked for comfort, and I learned that being sweet and helpful was how that affection '
                 'came.',
                 'I pulled myself together fast. I had to go on being the reason for pride, not the problem.',
                 'I was left with the impression that with me it was different, that the others got what I '
                 'was missing.',
                 'I kept it to myself. Showing what I felt meant opening a door that does not close '
                 'afterwards.',
                 'I watched the adult’s mood. I never knew whether comfort or a telling-off was coming.',
                 'I turned the page quickly and found a distraction. Sitting there hurting led nowhere.']},
 'f1_02': {'c': 'As a child, how did you get people to pay attention to you?',
           'a': ['By being liked and useful. Whoever takes care of others becomes someone you do not give '
                 'up.',
                 'By being a reason for pride. I was worth what I could show.',
                 'I did not manage to, and that confirmed that I lacked what the others had to spare.',
                 'By being the well-behaved one. With no grounds for criticism, approval came on its own.',
                 'By standing up to them. If I was strong, nobody would walk over me.',
                 'I did not even try. What I really wanted was for there to be no tension because of me.',
                 'I did not compete. I preferred my own corner to having to expose myself to fit in.',
                 'By staying close to whoever protected me, and being useful to that person.',
                 'By livening the place up. Where there is fun, there is a place for me.']},
 'f1_03': {'c': 'When you asked for something at home (a toy, to go somewhere), what usually happened?',
           'a': ['I knew who to ask and how. With someone who liked me, it almost always worked.',
                 'If a no came, I found another way round. Going without was the one thing I could not do.',
                 'I insisted until I got it. Depending on other people’s goodwill was never my way.',
                 'I did not ask for much. It had to be deserved, and at the right moment.',
                 'An explanation came about why it was not possible, and the feeling stayed that for others '
                 'it was.',
                 'I hardly ever asked. Asking already meant owing something to someone.',
                 'I asked with fear, not knowing whether a yes, a no or a telling-off was coming.',
                 'I hardly knew what I wanted. I went along with whatever the adults decided.',
                 'I showed that I deserved it: marks, chores done, something in return.']},
 'f1_04': {'c': 'When the adults at home argued, or the mood turned heavy, what did you usually do?',
           'a': ['I switched off and waited for it to pass. If I did not feel it, it did not reach me.',
                 'I got tense. Somebody there was in the wrong, and none of it should have been happening.',
                 'I stepped in, angry at whoever was being unfair to the weaker one.',
                 'I took care of whoever was worse off. If the mood came back, I had done my part.',
                 'I stayed alert, trying to predict how far it would go and what would land on me.',
                 'I got out of the way and shut myself in. That drained energy I did not have to give.',
                 'I felt it deeper than the others did, and carried it for days.',
                 'I carried on with my own things, showing that with me everything was fine.',
                 'I escaped into something else: television, a game, my imagination.']},
 'f1_05': {'c': 'Thinking about your family, which role ended up being yours?',
           'a': ['The responsible one, who could give no grounds for criticism.',
                 'The loved one, who took care of the others and was needed.',
                 'The one who did well, the family’s pride.',
                 'The one who did not fit, and felt that as a flaw of their own.',
                 'The one who asked for nothing, and did not want anything demanded of them either.',
                 'The loyal one, who held things together and could not let anyone down.',
                 'The one who lightened the mood.',
                 'The strong one, who sorted things out and protected people.',
                 'The easy-going one, who was no trouble and agreed with everything.']},
 'f1_06': {'c': 'Which of these conclusions did you reach early, without anyone having to teach it to you?',
           'a': ['“If I am not strong, people walk over me.”',
                 '“If I do not make trouble, everything stays peaceful.”',
                 '“If I get it wrong, criticism comes. It has to be done the right way.”',
                 '“If I am useful and well liked, they will not leave me behind.”',
                 '“If I do not stand out, I am not worth much.”',
                 '“Something in me was missing, and in other people it was not.”',
                 '“If I depend on anyone, they will intrude or let me down.”',
                 '“You cannot drop your guard. Trouble can come at any moment.”',
                 '“If I do not sort myself out, nobody is going to do it for me.”']},
 'f1_07': {'c': 'Someone important to you sends a message saying “we need to talk”, without saying what '
                'about. What goes through your head until the conversation?',
           'a': ['“What happened?” I have already imagined three scenarios, nearly all of them bad.',
                 'I go back over what might have gone wrong. If the fault is mine, I start blaming myself '
                 'already.',
                 'I think about how to come out of it well and not look bad.',
                 'If it is trouble, I will face it. What bothers me is being at someone’s mercy.',
                 'I push it away. I do not even think about it until I get there.',
                 'I already feel it is about me, that they are going to point out what I suspect about '
                 'myself.',
                 'I think about everything I have done for that person. It would be unfair of them to come '
                 'with complaints.',
                 'It bothers me to be caught with no time to prepare, exposed without having chosen it.',
                 'It is probably nothing. I am already thinking about something else.']},
 'f1_08': {'c': 'You are in a queue and someone cuts in front of you on purpose, and looks at you. What do '
                'you do?',
           'a': ['I speak up right away. Letting it go would mean accepting that people can push me back.',
                 'I am outraged. It is not about me: it is about that person doing something wrong.',
                 'I let it go. It is not worth turning into friction.',
                 'I get tense weighing the risk. If I speak, there is a scene; if I do not, I chew on it.',
                 'I do not make a scene. Fighting over a queue would make me look bad in front of everyone.',
                 'I am outraged that they would do that to me, of all people, who always show consideration '
                 'for others.',
                 'I feel it as a personal slight, as if I were not worth enough to be respected.',
                 'I say nothing. I am not going to spend my energy on a stranger.',
                 'I make a dry comment and move on. I am not ruining my day over this.']},
 'f1_09': {'c': 'A friend cancels at the last minute for the third time in a row. What happens?',
           'a': ['I am hurt. I am always there when they need me, and that builds up a debt they never pay.',
                 'I say it to their face, or I simply stop inviting them. I do not stay at anyone’s mercy.',
                 'I think it is disrespectful of other people’s time, even if I say nothing.',
                 'I am a bit annoyed and let it go. They must have their reasons.',
                 'I think they prefer other people’s company, and that gets to me more than it should.',
                 'I get a nagging feeling: are they avoiding me, or did something happen?',
                 'It is almost a relief. The evening is mine again, and it costs me less.',
                 'I fill the slot with something useful.',
                 'I call someone else or invent another plan. I do not sit there in the frustration.']},
 'f1_10': {'c': 'It is Saturday night, you are at home and no invitation came. What is that like for you?',
           'a': ['Great. That is when I get back what other people spend of me during the week.',
                 'I am fine with it. I let the evening go by without thinking much.',
                 'I start imagining what could be done. Having nothing on bothers me.',
                 'A feeling of being left out comes, as if the others had something I do not.',
                 'It feels odd. I am always available for other people, and nobody remembered me.',
                 'I am fine, but if nobody called, I start wondering why.',
                 'I use the time to get ahead on something. Standing still makes me feel I am falling '
                 'behind.',
                 'I use the time to put in order whatever is still pending.',
                 'If I want company, I call someone. I do not sit waiting to be remembered.']},
 'f1_11': {'c': 'In a group conversation, someone criticises something you did, in front of everyone. What '
                'happens inside you first?',
           'a': ['I think about how to recover my image right there.',
                 'Heat rises in me. Nobody is going to make me small in front of other people.',
                 'I check whether the criticism is fair. If it is, it hurts more, because I should have done '
                 'better.',
                 'I feel ashamed, and it confirms what I already suspected about myself.',
                 'I get suspicious of the person’s intentions, and of whoever is siding with them.',
                 'I am hurt. After everything I do, they could show me more consideration.',
                 'I go a bit numb. Only later do I notice how much it bothered me.',
                 'I close up and answer as little as possible. I am giving nothing away there.',
                 'I take it lightly and make a joke. I do not want to spoil the mood.']},
 'f1_12': {'c': 'You arrive at a party where you know hardly anyone. What do you do in the first twenty '
                'minutes?',
           'a': ['I look for the people there who are worth knowing.',
                 'I start conversations and go towards whoever looks like they need company.',
                 'I head for wherever it is liveliest. I came to enjoy myself.',
                 'I stay near the people I know until I understand the mood of the place.',
                 'I stick with whoever brought me and go at the group’s pace.',
                 'I hang back a little, feeling that I am not of that place.',
                 'I stay in a corner and watch. I would rather look than have to expose myself.',
                 'I walk right in and talk to whoever I want. I do not wait to be accepted.',
                 'I go a bit stiff, finding the conversations rather pointless.']},
 'f1_13': {'c': 'Someone important to you disappears for a week, with no explanation. What goes on?',
           'a': ['I already think I did something wrong, or that the person got tired of me.',
                 'I chew on what happened and on whether I can still trust them.',
                 'I am hurt, and I wait for them to notice that they miss me.',
                 'I say it straight when they turn up. Disappearing on me has consequences.',
                 'I take it easy. Everyone has their own timing.',
                 'I find it inconsiderate, even knowing there may be a reason.',
                 'I do not find it strange. People disappear when they want to, and I need my own '
                 'disappearances too.',
                 'I keep busy and carry on. We will sort it out when they come back.',
                 'I get on with my life, which is full of good things.']},
 'f1_14': {'c': 'You receive some unexpected money, enough to cover a month of expenses. What do you do with '
                'it?',
           'a': ['I save nearly all of it. Money sitting still is independence, and independence is not '
                 'needing anyone.',
                 'I put it in the reserve. It is for when something goes wrong.',
                 'I am already thinking of a trip, or something I have wanted for ages.',
                 'I spend a good part of it on the people I love. I like being the one who makes things '
                 'happen.',
                 'I invest it in something that makes me grow: a course, my appearance, equipment.',
                 'I pay off what is outstanding. Duty first, the rest afterwards.',
                 'I spend it on what I want, and I want it now.',
                 'I leave it in the account and use it on day-to-day comfort, with no plan.',
                 'I buy something with my face on it, something nobody else would have.']},
 'f1d_ie': {'c': 'You have just had an argument with someone. Twenty minutes later, what is still alive in '
                 'you?',
            'a': ['The body: tension, heat, the urge to sort it out or to walk off.',
                  'The scene: what the person thought of me, how I came across there.']},
 'f1d_im': {'c': 'You have to decide something important today and you do not have all the information. What '
                 'do you do?',
            'a': ['I decide with what I have and deal with the consequences later.',
                  'I put it off as long as I can, looking for more information or someone to confirm it.']},
 'f1d_em': {'c': 'On a bad night, what tends to keep you awake?',
            'a': ['A conversation, a look, someone who hurt me or did not value me.',
                  'Something unresolved, a risk, something that could go wrong tomorrow.']}}
