# -*- coding: utf-8 -*-
"""Traducao para ingles: Fase 2 (blocos de triade e desempates internos)."""

DADOS = {

# --- bloco instintivo (8, 9, 1) -------------------------------------------
'f2i_01': {'c': 'Someone close to you breaks an agreement with you for the second time. What do you do?',
 'a': ['I say it right away. Whoever lets it pass once teaches the other that they can do it again.',
       'I stop arguing. The person loses access to me, and they feel it.',
       'I let it go again. A row costs me more than swallowing it, though it does stick in my throat.',
       'I say nothing, and inside I stop counting on them. Arguing changes nobody.',
       'I explain what the agreement was. What gets me is not the trouble, it is the person thinking they can.',
       'I say it right away, and harshly, because that is unacceptable.']},

'f2i_02': {'c': 'Someone treated you badly yesterday. This morning, which thought turns up?',
 'a': ['“He will pay for it somehow.”',
       '“Not with me. He knows what happens if he tries it again.”',
       '“It is over, I am not chewing on it.”',
       '“He must be going through something.”',
       '“I would never treat anyone like that.”',
       '“That is wrong and I am not letting it slide.”']},

'f2i_03': {'c': 'You went somewhere in person to sort something out and, when your turn comes, they say a document is missing that was not on the list. What do you do?',
 'a': ['I demand to speak to whoever is in charge. I am not losing my day over a requirement they invented.',
       'I push until they make an exception. Whoever takes the first no always comes out losing.',
       'I come back another day. Arguing there would cost me more than the wasted trip.',
       'I do not complain there, and afterwards I drag my feet until I sort it out some other way.',
       'I say the information was wrong and ask them to correct it. What outrages me is the mistake, not the wasted trip.',
       'I am outraged at the carelessness, even knowing it is not that person’s fault.']},

'f2i_04': {'c': 'You got very angry this week. How did it go?',
 'a': ['I blew up, sorted it out on the spot, and afterwards it had already passed.',
       'I did not blow up, but I made it absolutely clear who was in charge there.',
       'I cannot even remember being angry. It must have passed on its own.',
       'I swallowed it at the time, and later it came out all at once, out of proportion.',
       'I held it in, went tense, and it turned into criticism, sarcasm or a headache.',
       'I said what had to be said, with indignation, because I was right.']},

'f2i_05': {'c': 'In your house, when you were a child, how did authority work?',
 'a': ['It was harsh, and early on I learned to hit back or to fend for myself.',
       'Someone had to protect the weaker ones in the house, and it fell to me.',
       'They decided for me, and agreeing was easier than arguing.',
       'Everyone to their own. I did my part and did not get involved.',
       'A lot of demands and criticism. I had to be the well-behaved one.',
       'There was a rule for everything, and I was the first to insist they were kept.']},

'f2i_06': {'c': 'In a family argument that heats up, what do you do?',
 'a': ['I raise my voice and take the lead. Whoever hesitates there becomes the target.',
       'I step in front of whoever is being attacked.',
       'I agree with everyone and switch off. If I do not feel the fight, it does not reach me.',
       'I try to calm both sides. That mood inside the house is unbearable to me.',
       'I keep my composure and point out who is right and who is wrong.',
       'I lose my temper defending what is right, and afterwards I blame myself for losing my composure.']},

'f2i_12': {'c': 'In an argument with people you know, with others watching, what do you do?',
 'a': ['I take them on in front of everyone. Backing off there would mean admitting they can walk over me.',
       'I defend whoever is on my side and make it clear that anyone who touches them deals with me.',
       'I give in and look for a middle ground, just to end the bad feeling.',
       'I keep quiet there and carry on doing it my way afterwards.',
       'I keep my composure and defend what is right.',
       'I point out the mistake in front of everyone, because that cannot pass.']},

'f2i_07': {'c': 'Someone close says: “sometimes you are difficult.” What do you agree with?',
 'a': ['I am too hard, and I hurt people before I notice.',
       'I do not show weakness, not even to the people I love.',
       'I settle for less and put aside what I want.',
       'I disappear from anything unpleasant until the deadline blows up.',
       'I am too demanding, with myself and with others.',
       'I get intolerant when things are not done properly.']},

'f2i_13': {'c': 'You said something rude to someone who did not deserve it. What happens afterwards?',
 'a': ['I turn the page. I do not sit there blaming myself.',
       'If the person provoked it, I do not feel much.',
       'The bad mood bothers me and I want the peace back.',
       'I act as if it had not happened.',
       'I feel heavy guilt, because I should have controlled myself.',
       'I think I was right, but I hold it against myself for losing my composure.']},

'f2i_08': {'c': 'An injustice you suffered years ago comes back into your head. What comes with it?',
 'a': ['The urge to settle that score one day.',
       'The lesson never to be that vulnerable again.',
       'Almost nothing. It was long ago and I do not want to stir it up.',
       'I think that, deep down, it was not that serious.',
       'Indignation. That was wrong and somebody needs to acknowledge it.',
       'A silent resentment that I never told anyone about.']},

'f2i_09': {'c': 'A friend is about to introduce you to someone who knows nothing about you. What do they probably say?',
 'a': ['That I am intense and good to have around when things get hard.',
       'That I am direct and do not accept disrespect.',
       'That I am easy-going and easy to live with.',
       'That I am stubborn: I agree and then do it my way.',
       'That I am reliable and do things properly.',
       'That I am demanding and fight for what I believe in.']},

'f2i_10': {'c': 'You have just had news that shook you. What do you do in the next hour?',
 'a': ['I act straight away: I call, I sort things, I do something. Standing still, I feel too much.',
       'I go out, drink, train, work double. I need to discharge it.',
       'I eat something, put the television on. If I do not touch it, it passes eventually.',
       'I carry on with the routine as if nothing had happened. It is the routine that keeps me standing.',
       'I turn it into a task: I organise, I sort out what I can. Sitting there feeling fixes nothing.',
       'I channel it into something useful, or into a cause.']},

'f2i_11': {'c': 'Someone you love says that you smother them. Which criticism lands closest?',
 'a': ['I confuse protecting with giving orders.',
       'I want the person all to myself, and I give little of myself.',
       'I adapt so much that what I wanted disappears.',
       'I run from the difficult conversation and let it drag on.',
       'I keep trying to improve the other person.',
       'I am too demanding about how the person should behave.']},

'f2i_14': {'c': 'About pleasure and excess: which scene is most yours?',
 'a': ['When I want something, I go all in, and I do not like being held back.',
       'I hate waiting for what I want.',
       'Small comfort every day: food, sofa, a series, and time goes by.',
       'I put off what I want, but nobody takes my routine away.',
       'Only once everything is done, and even then I police myself.',
       'I overdid it once and was left feeling I had done something wrong.']},

'f2i_15': {'c': 'A group has to decide something and nobody decides. What do you do?',
 'a': ['I decide and get on with it. We can fix what is wrong afterwards.',
       'I hand out the tasks and say who does what. If I do not take charge, someone takes charge of me.',
       'I wait for someone to decide and go with the majority. Having a position would only create friction.',
       'I let it ride. Sooner or later the decision sorts itself out.',
       'I propose the right way to do it and explain why it is best.',
       'I take it on, because I know I do it better than it would come out otherwise.']},

'f2i_16': {'c': 'Someone cries in front of you, in a hard situation. What happens to you?',
 'a': ['The fragility makes me uncomfortable and I want the person to react.',
       'I go straight to what solves it. Crying does not change the problem.',
       'I stay there, not quite knowing what to say, waiting for it to pass.',
       'I feel their pain as if it were mine and forget my own.',
       'I comfort them, but inside I think they need to pull themselves together.',
       'I think about what they could have done not to end up there.']},

'f2i_17': {'c': 'What is your Saturday usually like?',
 'a': ['Every Saturday is different, however I feel. I hate having a schedule at the weekend.',
       'I drag someone into something, and it usually goes far. Half measures bore me.',
       'Almost always the same. Changing takes energy I do not want to spend.',
       'I start several things and end up on the sofa, not quite knowing what I actually wanted.',
       'I have a list and I get through it. Resting with something pending leaves me in debt.',
       'I put right whatever went crooked during the week. It keeps calling me until I deal with it.']},

}
