# -*- coding: utf-8 -*-
"""Traducao para ingles: Fase 2, bloco emocional (2, 3, 4)."""

DADOS = {

'f2e_01': {'c': 'One day you feel good about yourself. What has usually happened?',
 'a': ['Someone came to me because they needed me.',
       'Someone treated me as special, made a fuss of me.',
       'I delivered something well made and it was recognised.',
       'I sorted everything out on my own, without needing anyone.',
       'I lived something true, mine, that nobody else would have lived the same way.',
       'I got through a heavy day without complaining, and I coped.']},

'f2e_02': {'c': 'Which of these sentences, said by someone important to you, would most ruin your day?',
 'a': ['“I do not need you.”',
       '“You are not as important to me as you think.”',
       '“You failed and let everyone down.”',
       '“You cannot be counted on.”',
       '“You are ordinary, just like everyone else.”',
       '“I prefer someone else to you.”']},

'f2e_03': {'c': 'You are very sad and someone brings it up. What do you do?',
 'a': ['I turn the conversation to them and end up taking care of them.',
       'I let a little of it out, hoping they will insist and look after me.',
       'I say everything is fine and keep functioning. Looking broken is the last thing I want.',
       'I change the subject and go back to what I was doing. Producing gets me out of there.',
       'I talk, and it goes deep. Feeling it whole is the truest thing I have.',
       'I cut it short. Complaining is weakness, I can take it.']},

'f2e_04': {'c': 'You are about to meet people who do not know you yet. What do you do before leaving the house?',
 'a': ['I think about how I will receive them, what to bring, how to put them at ease.',
       'I pick something that makes me charming, the way that usually works.',
       'I make sure I look presentable and think about what I will say about what I do.',
       'I do not dress up much. I would rather they noticed I am competent than that I am vain.',
       'I pick something with my face on it, even if it clashes with everyone else.',
       'I do not think about it much, and I find it rather shallow of those who do.']},

'f2e_05': {'c': 'You did something carefully for someone, and it was not what they expected. What comes first?',
 'a': ['Fear that they will like me less.',
       'Indignation: after everything I do, they still complain?',
       'A rush to fix it and show that I can cope.',
       'The urge to try twice as hard, quietly, until nobody has anything to say.',
       'The bitter confirmation that I am never enough.',
       'Resentment: nobody saw what that cost me.']},

'f2e_06': {'c': 'You spent the night helping a friend with a problem. They thank you lightly and change the subject. What is left?',
 'a': ['A hurt. I would have done much more for them.',
       'I wait for something back, without ever asking for it out loud.',
       'Nothing much. I solved it, and that is already worth it.',
       'I am satisfied at having been useful, even with no applause.',
       'A feeling that with other people they would have been warmer.',
       'Nothing. I do not help expecting anything back, and I am proud of that.']},

'f2e_07': {'c': 'You are in a group and someone tells you about a big achievement. What stirs in you?',
 'a': ['The affection that person gets, which I would like too and do not ask for.',
       'Them taking the spotlight that is usually mine.',
       'The recognition. It is what I am after as well.',
       'Seeing someone less competent being valued more.',
       'That the person seems whole and at peace, which I have never felt.',
       'That they got easily what cost me a great deal.']},

'f2e_12': {'c': 'Which gesture from someone makes you feel really loved?',
 'a': ['Coming to me when they need something. Seeing that I am missed.',
       'Treating me as the favourite, above everyone else.',
       'Being proud of me in front of other people.',
       'Recognising everything I do and how much I can be counted on.',
       'Understanding me in a way nobody else does.',
       'Taking care of me without my having to ask.']},

'f2e_08': {'c': 'In a relationship, what are you most afraid will happen?',
 'a': ['That the person finds out they can live perfectly well without me.',
       'That I stop being their priority.',
       'That the person stops admiring me.',
       'That the person sees I am not as secure as I look.',
       'That the person never really gets to know me.',
       'That they become more interested in someone else than in me.']},

'f2e_09': {'c': 'A relationship of yours ended badly. Looking back, what was your part in it?',
 'a': ['I gave too much and waited for something back without ever asking.',
       'I won them over and then demanded total devotion.',
       'I looked after the image of the couple more than the relationship.',
       'I became what the other person wanted and lost myself on the way.',
       'I undervalued what was there and wanted what was missing.',
       'I turned the relationship into a contest, between love and anger.']},

'f2e_10': {'c': 'You wake up on Sunday with nothing planned and nobody around. What is the first hour like?',
 'a': ['I am already texting someone. On my own, I am no use for anything.',
       'It bothers me that nobody remembered me.',
       'I make a list and start getting ahead. Standing still, I feel I am falling behind.',
       'I tidy the house, clear what is pending. Without producing, it is as if I were worth nothing.',
       'A melancholy comes over me and I stay in it for a while.',
       'I get up and go and work on something, because stopping hurts more.']},

'f2e_11': {'c': 'Which of these compliments would you still remember years later?',
 'a': ['“I do not know what would become of me without you.”',
       '“You are the most charming person I know.”',
       '“You are impressive at what you do.”',
       '“With you, everything works.”',
       '“I have never met anyone like you.”',
       '“I admire your strength, after everything you have been through.”']},

'f2e_13': {'c': 'Someone close to you got exactly what you wanted. What happens inside?',
 'a': ['I am happy for them and, deep down, I hope they carry on needing me.',
       'I feel I deserved it too, and I hope someone notices.',
       'I speed up to show that I can do it as well.',
       'I play it down and carry on with my work, without letting it show.',
       'It hurts, because it looks as if for other people it is easier.',
       'It turns into fuel to try harder, or into the urge to belittle what they achieved.']},

'f2e_14': {'c': 'In your house, as a child, what made an adult look at you with pride?',
 'a': ['My being affectionate, helpful, the darling.',
       'My being charming with visitors.',
       'My doing well: marks, prizes, results.',
       'My sorting things out alone, giving no trouble.',
       'Almost nothing. I felt another child got that look.',
       'My holding firm and helping, even as a child.']},

'f2e_15': {'c': 'In a conversation, someone asks about a subject you hardly know. What do you do?',
 'a': ['I steer it into a story of mine and the table comes along.',
       'I say I do not know, but I charm them another way.',
       'I speak with confidence anyway. I can catch up afterwards.',
       'I steer it to the part I do know, and nobody notices.',
       'I admit it, but it bothers me that other people know more than I do.',
       'I make it clear that the subject is shallow and does not interest me.']},

'f2e_16': {'c': 'Someone asks how you are really feeling. What happens?',
 'a': ['I talk about what I feel for other people before talking about myself.',
       'I well up straight away, and the whole conversation becomes that.',
       'I answer that I am fine almost automatically, and it takes me a while to know what I feel.',
       'I talk about what I am doing, not about what I am feeling.',
       'I talk, and it goes deep. That matters more than the rest.',
       'I change the subject. Talking about it exposes me too much.']},

'f2e_17': {'c': 'You told a story to a group yesterday. How did it go?',
 'a': ['I put feeling and gesture into it, and the table came along. I like being the one who moves people.',
       'I exaggerated a little to make the story better.',
       'I told it the way that works. I already know the effect it has.',
       'I got straight to the point. What counts is the effect, not the decoration.',
       'I told them what it meant to me.',
       'I hardly spoke. I thought nobody would be interested.']},

}
