# -*- coding: utf-8 -*-
"""Traducao para ingles: Fase 2, bloco mental (5, 6, 7)."""

DADOS = {

'f2m_01': {'c': 'You are unsure about an important decision and it will not leave your head. What do you do?',
 'a': ['I withdraw and sort it out alone. Asking for help already leaves me owing something.',
       'I talk to the one person I really trust, and to nobody else.',
       'I ask someone reliable for their opinion and I am still in doubt afterwards.',
       'I force the decision through, so as not to be held hostage by the doubt.',
       'I keep the options open. Closing one means giving up all the others.',
       'I keep busy helping someone else and put my own decision off.']},

'f2m_02': {'c': 'What makes you want to cancel a commitment you have already made?',
 'a': ['Knowing it is going to eat up my energy and my time.',
       'Feeling that they will demand a closeness I do not want to give.',
       'Not quite knowing who will be there or what will happen.',
       'Feeling that someone there wants to test me or control me.',
       'Something more interesting turning up.',
       'Realising it was me giving myself away again with nobody noticing.']},

'f2m_03': {'c': 'You want something badly (to travel, to change jobs, to tell someone how you feel). What happens?',
 'a': ['I talk myself into believing I can live without it.',
       'I go on wanting it in silence, and hardly anyone finds out.',
       'I weigh the risks and put it off.',
       'Sometimes I go all in at once, so as not to let myself freeze.',
       'I go after it. Putting off pleasure is a waste.',
       'I hold back in the name of something bigger, and I am left feeling I am missing my life.']},

'f2m_04': {'c': 'First day of a course. The person running it says they will be marking each person’s participation over the classes. What goes through your head?',
 'a': ['I am already working out the minimum I need to show up so as not to expose myself more than necessary.',
       'I will only take their assessment seriously if it becomes clear that they know the subject.',
       'I want to know what the criterion is, and I already suspect it could be unfair.',
       'I test how far their ruler goes straight away, so I know where I am standing.',
       'I do not take it very seriously. I will find a way to do it my way and enjoy it too.',
       'I offer to help straight away. Being useful and pleasant, nobody really holds me to account.']},

'f2m_05': {'c': 'In your house, as a child, what gave you security (or what was missing)?',
 'a': ['I had little space of my own, and disappearing was my way out.',
       'I preferred to understand people from a distance rather than deal with them.',
       'The mood changed with somebody’s temper, and I lived on alert.',
       'I felt I had to be strong, because there was nobody to count on.',
       'Things were short, and I learned early to manage and to enjoy myself with little.',
       'I was the one who lifted everybody when things got tight.']},

'f2m_06': {'c': 'An old friend makes a toast to you and names a quality of yours. Which of these would make you think they really know you?',
 'a': ['That you need very little and never ask anyone for anything.',
       'That you think for yourself and do not follow the herd.',
       'That you are loyal and always keep your word.',
       'That you are not intimidated by anyone.',
       'That you make the most of life and see the good side of everything.',
       'That you give yourself to others expecting nothing in return.']},

'f2m_07': {'c': 'You have had bad news about someone’s health in the family. What is your week like?',
 'a': ['I go quiet, deal with the practical side and process it alone.',
       'I pull away from everyone for a while until I can handle it.',
       'I run through every scenario and what to do in each one.',
       'I harden up, take charge, and let nobody see that it shook me.',
       'I pull out the good side, make jokes, keep the mood light.',
       'I keep busy looking after everyone and never stop to feel it.']},

'f2m_12': {'c': 'Someone tells you a version of a story that does not add up. What do you do?',
 'a': ['I keep the doubt to myself and gather information. Asking would mean giving away what I think.',
       'I study until I know the subject inside out. Understanding is the only security that depends on nobody.',
       'I look for someone reliable to tell me which version to believe.',
       'I confront the person until the explanation holds up.',
       'I go with the lighter version and move on.',
       'I fit it into a bigger idea that makes sense.']},

'f2m_08': {'c': 'A friend is about to introduce you to someone who knows nothing about you. What do they say?',
 'a': ['That I am private and hard to know completely.',
       'That I am closed off, but intense with whoever gets in.',
       'That I am loyal and take everything seriously.',
       'That I am firm and do not drop my guard.',
       'That I am lively and full of ideas.',
       'That I am helpful and idealistic.']},

'f2m_09': {'c': 'The person you are with wants more closeness than you do. What do you do?',
 'a': ['I pull back and keep a space nobody enters.',
       'I demand total transparency and close up if they break it.',
       'I test their loyalty and look for signs that I am going to get hurt.',
       'I keep my guard up even when I care a great deal.',
       'I look for novelty when things get heavy.',
       'I fall in love with the idea of the relationship and get frustrated with the daily reality.']},

'f2m_10': {'c': 'Which scene best describes a quiet day for you?',
 'a': ['Nobody asking anything of me and time to spare.',
       'Few commitments and nobody depending on me.',
       'Everything planned, bills paid, nothing outstanding.',
       'Feeling that I am ready for whatever comes.',
       'Good things in the diary for the week.',
       'Seeing that the people around me are well because of something I did.']},

'f2m_11': {'c': 'Which of these compliments would you still remember years later?',
 'a': ['“You see what nobody else sees.”',
       '“You have a brilliant mind.”',
       '“You are the most reliable person I know.”',
       '“You are brave, you are afraid of nothing.”',
       '“Life is lighter with you around.”',
       '“You are a good person, someone who thinks of everyone.”']},

'f2m_13': {'c': 'You are alone at home at night and you hear a strange noise. What do you do?',
 'a': ['I stay still, listening, weighing it up. Acting without understanding is the worst way to spend energy.',
       'I lock everything and go back to my corner, which is where nothing reaches me.',
       'I imagine the worst straight away and check the door, the windows, everything.',
       'I pick something up and go and look it in the face.',
       'It must be the wind. I go back to what I was doing.',
       'I rationalise it quickly and convince myself it is nothing.']},

'f2m_14': {'c': 'Someone chases you about something you did not deliver. What happens?',
 'a': ['On the outside I agree, on the inside I resist being chased at all.',
       'I am left with a guilt I show to nobody.',
       'I blame myself first, and right afterwards I think there was a failure on their side too.',
       'I explain my reasons point by point and defend myself.',
       'I promise it for right away and find a way to come out of it well.',
       'I play it down. It was not that important anyway.']},

'f2m_15': {'c': 'You had two hours to yourself, with no obligations at all. Where did your head go?',
 'a': ['To a subject I want to understand deeply.',
       'To organising what I already know, without having to tell anyone.',
       'To a theory about how things really work.',
       'To a problem I need to solve before it becomes a problem.',
       'To plans: a trip, a project, possibilities.',
       'To a new idea I already want to tell someone about.']},

'f2m_16': {'c': 'An acquaintance asks a big favour that will take up your whole weekend. What do you do?',
 'a': ['I make an excuse. My time is mine.',
       'I do it, but counting the minutes, and I do not offer again.',
       'I do it, because I said I would and I do not go back on my word.',
       'I do it, but I keep wondering what they will want next.',
       'I do it if it is fun. If not, I pass it to someone else.',
       'I promise on the spot and work out later how to get out of it.']},

}
